version: 2.1
jobs:
    build:
        docker:
            - image: cimg/base:latest
        steps:
            - checkout

            - run:
                name: Check for 'master' branch
                command: [[ -z "$(git branch --all --list master */master)" ]]
