version: 2.1
jobs:
    build:
        docker:
            - image: cimg/base:stable

        steps:
            - checkout

            - run:
                name: Check for 'master' branch
                command: |
                    git fetch --all --quiet --prune --prune-tags
                    if [[ -n "$(git branch --all --list master */master)" ]]; then
                        echo "A branch named 'master' was found. Please remove it."
                        echo "$(git branch --all --list master */master)"
                    fi
                    [[ -z "$(git branch --all --list master */master)" ]]
